name = "Bearcraft"
author = "bearfm"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c49f1db426375e81dd152a5db1ec7ce387a67037253e903526ad1e637af43bfb"

[versions]
fabric = "0.17.2"
minecraft = "1.21.7"

[options]
acceptable-game-versions = []
