name = "Bearcraft"
author = "bearfm"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00dc073cf79aa922f57e27627094e21a5b158dc8c79a8f4705a3c6bbbfd0a6e0"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
